spring:
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:C:/SQLite/students.db
    username: rootuser
    password: trust
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
  flyway:
    user: rootuser
    password: trust
    schemas: main
    validate-on-migrate: true
    baseline-on-migrate: true
server:
  port: 8083
  servlet:
    context-path: /students-service